document.write( '<div id=\"accordion\" class=\"footer\">\n' );
document.write( '  <div class=\"card\">\n' );
document.write( '    <div class=\"card-header\" id=\"blockchainfooter\" style=\"background-color:#B3E5FC; color:black; padding:.65rem 1.25rem\">\n' );
document.write( '      <h5 class=\"mb-0\">\n' );
document.write( '        <button class=\"btn btn-link\" data-toggle=\"collapse\" style=\"background-color:#B3E5FC; color:#155724;\" data-target=\"#collapseblockchainfooter\" aria-expanded=\"false\" aria-controls=\"collapseblockchainfooter\" >\n' );
document.write( '           Would appreciate any <span style=\"color:blue;\"><b>donation</b></span> to keep this website simple and ad-free. Spread the crypto-love &#x2665 \n' );
document.write( '        </button>\n' );
document.write( '      </h5>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div id=\"collapseblockchainfooter\" class=\"collapse\" aria-labelledby=\"blockchainfooter\" data-parent=\"#accordion\">\n' );
document.write( '      <div class=\"card-body\" style=\"background-color:#ffffff;\">      \n' );
document.write( '		  <b>Ethereum/Polygon :</b> 0x0E678aCf9988e284f448C6224Ea36bb9E9d56803 <br>\n' );
document.write( '          <b>Cosmos :</b> cosmos18hjgges2wkmntaewy84974yqdeh45u40z2wxug <br>\n' );
document.write( '      </div>\n' );
document.writeln(" <center> <img src=\"donate.png\" alt=\"donate\"></img></center> ");
document.write( '    </div>\n' );
document.write( '  </div>\n' );
document.write( '  \n' );
document.write( '</div>' );
